### ISSUE TITLE
[Feature Request]: Consistent Release Pipeline to PyPI

### ISSUE THREAD

**Issue by wieluk** [psychopy/psychopy#7054]
### Description

It seems like versions are not automatically released to pypi. It would be nice to have a consistent release to pypi. 

This is a mininal example:
```
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install build twine
          python -m build
          python -m twine upload --repository pypi dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} --non-interactive
```

To make it work with tags you might need some changes to the pyproject.toml.

```
[build-system]
requires = ["setuptools_scm"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "no-local-version"
```

The trigger could be a restricted tag following a specific structure, such as:
```
on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9]+.[0-9]+'  # Matches tags like 2023.1.0, 2024.12.3, etc.
```
